@startuml
note "Tous les attributs sont NOT NULL" as N1
abstract class Logiciel{
  NomDeve: string {key}
  Nom: string {key}
  DateLancement: date
}
class Version{
  Numéro: int {local key}
  DateDisponibilité: date
}
class Problème{
  Date: date
  Description: string
}
abstract class Correctif{
  Date: date
}
class InstructionTextuelle{
  Instruction: string
}
class PatchCorrectif{
  ID: integer {key}
}
abstract class Personne{
  Nom: string
  Prénom: string
  DateNaissance: date
}
abstract class Personne
class Employé{
  Poste: integer
}
class Employé
note top: {(Nom,Prénom,DateNaissance,Poste) key}
class Client{
  Adresse: string
  Téléphone: integer {key}
}
class Achat{
  Date: date
}
class Achat
note LEFT: {(Client,Logiciel,Date) key\n\nDate>DateLancement}
class OS
abstract class Programme{
  Type: string
}
class Application
class Jeu
class Plateforme{
  Type: string
}
class ProgrammeType{
  Type: string
}

Client-- Employé
Personne <|-- (Client, Employé)
note top on link
XOR
end note
Employé "1" -"0..N" Correctif: responsable >
InstructionTextuelle - PatchCorrectif
Correctif <|-- (InstructionTextuelle,PatchCorrectif)
note right on link
XOR
end note
Client "1..N" - "0..N" Problème: fait remonter >
Problème "1" ---"0..N" Correctif: apporté au <
Version "1"---"0..N" Problème : detecte sur <
Logiciel *-- "1..N" Version
Logiciel "1..N" ---"0..N"Client : achète <
Achat..(Client,Logiciel)
Logiciel <|-- (Programme,OS)
note right on link
XOR
end note
Programme "0..N"---"1..N" OS: supporte >
OS "1..N"-"1..N" Plateforme: supporte >
Application-Jeu
Programme <|-- (Application,Jeu)
note right on link
XOR
end note
Programme "0..N" - "1..N" ProgrammeType: est >

@enduml